spring:
  profiles: dev

  application:
    name: config-serve-dev
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  
mybatis:
  type-aliases-package: com.aaa.fan.springcloud.entity
  mapper-locations: classpath:mapper/*Mapper.xml

eureka:
  client:
    server:
    eviction-interval-timer-in-ms: 7000 
    registerWithEureka: false #是否从Eureka Server查询注册信息
    fetchRegistry: false #是否将自己注册到Eureka Server 默认为true
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 8
    hostname: localhost

info:
  author:
    name: fan
  company:
    name: AAA
  project:
    description:BookDemo

    
  
